---

- name: install mesosphere-zookeeper
  yum: state=present name=mesosphere-zookeeper

- name: configure zookeeper
  template: src=etc/zookeeper/conf/zoo.cfg.j2
            dest=/etc/zookeeper/conf/zoo.cfg
            mode=0444 owner=root group=root
  notify: bounce zookeeper

- name: start zookeeper
  service: name=zookeeper state=started enabled=yes
