- include: storage.yml

- name: install mesos RPM
  yum: name={{ mesos_rpm }} state=present
  notify: bounce mesos slave

- name: mesos work dir
  file: path={{ mesos_work_dir }} state=directory

- name: configure slave
  template: src=.{{ item }}.j2  dest={{ item }}
            mode=0444
  with_items:
    - /etc/mesos-slave/cgroups_enable_cfs
    - /etc/mesos-slave/?cgroups_limit_swap
    - /etc/mesos-slave/containerizers
    - /etc/mesos-slave/executor_registration_timeout
    - /etc/mesos-slave/isolation
    - /etc/mesos-slave/switch_user
    - /etc/mesos-slave/work_dir
    - /etc/mesos/zk
    - /etc/default/mesos
  notify: bounce mesos slave

- name: enable mesos slave service
  service: name=mesos-slave state=running enabled=yes

- name: disable mesos master service
  service: name=mesos-master state=stopped enabled=no
