---

- hosts: all
  sudo: yes
  tasks:
    - name: ansible prerequisites
      yum: name=libselinux-python state=present

# masters up first, since they
# should be upgraded before slaves

- hosts: masters
  sudo: yes
  roles:
    - mesos/master

- hosts: slaves
  sudo: yes
  roles:
    - mesos/slave

- hosts: zookeepers
  sudo: yes
  roles:
    - zookeeper
