---

# masters up first, since they
# should be upgraded before slaves

- hosts: masters
  sudo: yes
  roles:
    - repo/mesosphere
##     - mesos/master
- hosts: slaves
  sudo: yes
  roles:
    - repo/mesosphere
##     - mesos/slave
- hosts: zookeepers
  sudo: yes
  roles:
    - java8
    - repo/mesosphere
    - zookeeper
