---

# masters up first, since they
# should be upgraded before slaves

- hosts: masters
  become: yes
  roles:
    - repo/mesosphere
    - mesos/master
- hosts: slaves
  become: yes
  roles:
    - repo/mesosphere
    - docker
    - mesos/slave
- hosts: zookeepers
  become: yes
  roles:
    - java8
    - repo/mesosphere
    - zookeeper
