---

- name: mesosphere RPM repo
  template: src=etc/yum.repos.d/mesosphere.repo.j2
            dest=/etc/yum.repos.d/mesosphere.repo
            mode=0444 owner=root group=root

- name: mesosphere RPM GPG key
  copy: src=etc/pki/rpm-gpg/RPM-GPG-KEY-mesosphere
        dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-mesosphere
        mode=0444 owner=root group=root
