---

- name: install mesos RPM
  yum: name={{ mesos_rpm }} state=present
  notify: bounce mesos

- name: mesos work dir
  file: path={{ mesos_work_dir }} state=directory

- name: common config
  template: src=etc/default/mesos.j2
            dest=/etc/default/mesos
            mode=0444
  notify: bounce mesos

- name: remove old config
  file: name={{ item }} state=absent
  with_items:
    - /etc/mesos-slave/ip
    - /etc/mesos-master/ip
  notify: bounce mesos

- name: setup zookeeper config
  template: src=etc/mesos/zk.j2 dest=/etc/mesos/zk
            mode=0444
  notify: bounce mesos
