- name: install mesos RPM
  yum: name={{ mesos_rpm }} state=present
  notify: bounce mesos master

- name: mesos work dir
  file: path={{ mesos_work_dir }} state=directory

- name: configure master
  template: src=.{{ item }}.j2  dest={{ item }}
            mode=0444 owner=root group=root
  with_items:
    - /etc/default/mesos
    - /etc/mesos/zk
    - /etc/mesos-master/work_dir
    - /etc/mesos-master/quorum
    - /etc/mesos-master/registry
  notify: bounce mesos master

- name: enable mesos master service
  service: name=mesos-master state=running enabled=yes

- name: disable mesos slave service
  service: name=mesos-slave state=stopped enabled=no
