---

- name: get latest event mapper libs
  yum: name=device-mapper-event-libs state=latest

- name: install docker
  yum: name=docker-io state=present

- name: start docker service
  service: name=docker state=started enabled=yes
