# needed by masters and slaves (since 0.19)
mesos_work_dir: /var/mesos
# default from RPM
mesos_log_dir: /var/log/mesos
mesos_maxfiles: 64000

# slave specific

mesos_isolation: cgroups/cpu,cgroups/mem

# or 'true' - don't use 'bare' bools!
mesos_switch_user: "false"
# CFS = 'hard limits'. if off, it's burstable
mesos_cgroups_enable_cfs: "false"
